config/routes.rb
Rails.application.routes.draw do

  get 'experiment_result_package/edit'

  root 'experiment#home2'

  get 'select-experiment' => 'experiment#home2'

  get 'home' => 'experiment#home2'

  get 'experiment_results/create'

  get 'purchases/create'

  get 'product_categories/index'

  resources :experiment_groups
  resources :experiment_clicks
  resources :experiment_product_selects
  resources :experiment_product_views
  resources :experiment_category_views
  resources :experiment_product_detail_views
  resources :purchases
  resources :experiment_results
  resources :experiment, only: [:index]
  resources :participants, only: [:create]
  resources :experiment_result_package, only: [:update]

  post 'participants/:access_token/select-experiment' => 'participants#select_experiment'
  get 'product_categories/:id/:access_token' => 'product_categories#show'

  get 'experiment/home'

  post   'new_participant'   => 'sessions#create'
  delete 'end_participation'  => 'sessions#destroy'

  get 'select_experiment'     => 'sessions#select_experiment'
  post 'assign_experiment_group' =>  'sessions#assign_experiment_group'
  get 'assign_experiment_group/:experiment_id' => 'sessions#assign_experiment_group', as: 'assign_to_group'

  devise_for :admins,
             controllers: {
                 sessions: 'admins/sessions',
                 registrations: 'admins/registrations'
             },
             path: '/admin',
             path_names: {
                 sign_in: 'login'
             }

  namespace :admin do
    root :to => "static_pages#index"
    get 'experiment_results/home'
    get 'experiment_results/index/experiment/:id'   => 'experiment_results#index', as: :experiment_results_home_index
    delete 'experiment_results/index/experiment/:id' => 'experiment_results#destroy', as: :experiment_results_home_destroy 
    get 'experiment_results/purchases/participant/:id' => 'experiment_results#purchases', as: :experiment_results_purchases
    resources :experiments do
      resources :experiment_groups
    end
    put 'experiments/:id/make_available/' => 'experiments#make_available', as: :make_experiment_available
    put 'experiments/:id/make_unavailable' => 'experiments#make_unavailable', as: :make_experiment_unavailable
    resources :experiment_groups
    get 'experiment_groups/:experiment_id/add_to_experiment' => 'experiment_groups#add_to_experiment', as: :add_to_experiment
    get 'experiment_groups/:experiment_id/show_groups' => 'experiment_groups#index', as: :show_experiment_groups
    get 'experiment_groups/:id/add_all_categories' => 'experiment_groups#add_all_categories', as: :add_all_categories
    get 'experiment_groups/:id/delete_all_categories' => 'experiment_groups#delete_all_categories', as: :delete_all_categories
    get 'experiment_groups/group/:group_id/category/:category_id/remove_category' => 'experiment_groups#destroy_category', as: :destroy_category
    get 'experiment_groups/group/:group_id/category/:category_id/add_category' => 'experiment_groups#add_category', as: :add_category
    resources :categories do
      get 'products_by_category' => 'products#index_by_category'
      resources :products
    end
    resources :products do
      resources :product_images
    end
    get 'product-categories/' => 'products#product_categories_home', as: :home_products
    resources :product_images
    get 'product_images/:product_id/new' => 'product_images#new', as: :new_product_image
    get 'product_images/make_main_image/product/:product_id/image/:product_image_id' => 'product_images#make_main_image', as: :make_main_image
    post 'save-group-category-order' => 'experiment_group_categories#save_group_category_order'
  end

end

app/models/experiment.rb
# == Schema Information
#
# Table name: experiments
#
#  id                       :integer          not null, primary key
#  name                     :string
#  available                :boolean
#  survey_link              :string
#  experiment_group_counter :integer          default(0)
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  completion_message       :string
#  show_survey_link         :boolean
#

class Experiment < ActiveRecord::Base
  # Scopes
  scope :available, -> { where(available: true)}

  has_many :experiment_groups, autosave: true, dependent: :delete_all

  # Has Many Experiment Results
  has_many :experiment_results, -> { order('created_at ASC') }, inverse_of: :experiment

  # Has Many Clicks
  has_many :experiment_clicks,  -> { order('created_at ASC') },inverse_of: :experiment

  # Has Many Product Placements
  has_many :experiment_product_placements, -> { order('created_at ASC') }, inverse_of: :experiment

  # Has Many Product Selects
  has_many :experiment_product_selects, -> { order('created_at ASC') }, inverse_of: :experiment

  # Has Many Product Views
  has_many :experiment_product_views, -> { order('created_at ASC') }, inverse_of: :experiment

  # Has Many Experiment Category Views
  has_many :experiment_category_views, -> { order('created_at ASC') }, inverse_of: :experiment 

  # Has Many Experiment Product Detail Views
  has_many :experiment_product_detail_views, -> { order('created_at ASC') }, inverse_of: :experiment

  # Has Many Purchases
  has_many :experiment_purchases, -> { order('created_at ASC') }, inverse_of: :experiment

  # Has Many Participants
  has_many :participants, -> { order('created_at ASC') }, inverse_of: :experiment

  validates :name, presence: true
end

app/controllers/admin/experiments_controller.rb
class Admin::ExperimentsController < ApplicationController
  layout "admin"
  before_action :authenticate_admin!

  def index
    @experiments = Experiment.all
  end

  def show
    @experiment = Experiment.includes(:experiment_groups).find(params[:id])
  end

  def new
    @experiment = Experiment.new
  end

  def create
    experiment = Experiment.new(experiment_params)
    if experiment.save
      flash[:success] = "Experiment, #{experiment.name}, was successfully created"
      redirect_to admin_experiment_path(experiment)
    else
      flash[:error] = "An error occurred. Please try again"
      redirect_to new_admin_experiment_path
    end
  end

  def edit
    @experiment = Experiment.find(params[:id])
  end

  def update
    experiment = Experiment.find_by({id: params[:id]})
    if experiment.update_attributes(experiment_params)
      redirect_to admin_experiment_path experiment
    end
  end

  def destroy
    @experiment = Experiment.find(params[:id])
    if @experiment.destroy
      flash[:success] = 'The experiment has been successfully deleted'
      redirect_to admin_experiments_path
    else
      flash[:error] = 'There was a problem in attempting to delete the experiment. Please try again. If the problem persists, contact your administrator'
      redirect_to admin_experiment_path @experiment
    end
  end

  def make_available
    experiment = Experiment.find(params[:id])
    experiment.available = true
    if experiment.save
      redirect_to admin_experiment_path experiment
    end
  end

  def make_unavailable
    experiment = Experiment.find(params[:id])
    experiment.available = false
    if experiment.save
      redirect_to admin_experiment_path experiment
    end
  end

  private
    def experiment_params
      params.require(:experiment).permit(:name, :available, :survey_link, :show_survey_link, :completion_message)
    end
end

app/controllers/experiment_controller.rb
class ExperimentController < ApplicationController
  layout 'application'


  def home
    @experiment_settings = ExperimentGroup.includes(:categories).find_by_id(current_participant.experiment_group)
    @experiment = Experiment.find(@experiment_settings.experiment_id)
  end

  def home2

  end

  def index
    @experiments = Experiment.includes(experiment_groups: [experiment_group_categories: [:category]]).available
    respond_to do |format|
      format.json {
          render :json => @experiments.to_json(:include => {
              :experiment_groups => {
                  :include => {
                      :experiment_group_categories => {
                          :include => :category
                      }
                  }
              }
          })
      }
    end
  end

end

app/helpers/admin/experiments_helper.rb
module Admin::ExperimentsHelper
end

app/helpers/experiment_helper.rb
module ExperimentHelper
end

app/views/experiment/_category.html.erb
<li>
  <%= link_to "#{category.name}", "#/category/#{category.id}", class: 'top-menu-category' %>
</li>

app/views/experiment/_side_category.html.erb
<%= link_to "#{side_category.name}", '#', class: 'list-group-item' %>

app/views/experiment/home.html.erb
<% @fontcolor = @experiment_settings.font_color || 'inherit' %>

<% if @experiment_settings.background_type == 'image' %>
    <% @background = "url(#{@experiment_settings.background_image.url}" %>
<% else %>
    <% @background = "#{@experiment_settings.background_color}" %>
<% end %>

<div class="row">
  <!-- Shopping Cart Position Left -->
  <% if @experiment_settings.cart_position == 'topleft' %>
      <div class="col-sm-1" id="shopping-cart">
        <a href="#/shopping-cart" class="pull-left text-center"><span class='glyphicon glyphicon-shopping-cart'></span><br/>View Cart</a>
      </div>
  <% end %>

  <!-- Logo File -->
  <div class="<% if @experiment_settings.cart_position == 'topleft' %> col-sm-offset-3 <% else %> col-sm-offset-4 <% end %> col-sm-4 text-center" id="logo">
    <%= image_tag "#{@experiment_settings.logo_filename}", class: 'img-responsive' %>
  </div>

  <!-- Shopping Cart Position Right -->
  <% if @experiment_settings.cart_position == 'topright' %>
      <div class="col-sm-4" id="shopping-cart">
        <a href="#/shopping-cart" class="pull-right text-center"><span class='glyphicon glyphicon-shopping-cart'></span><br/>View Cart</a>
      </div>
  <% end %>
  <div class="clearfix"></div>
</div>

<!-- Top Menu with Categories -->
<div class="row">
  <nav class="navbar navbar-default" id="category-menu" role="navigation">
    <div class="container">
      <div>
        <!-- Categories Assigned to Experiment Group -->
        <ul class="nav navbar-nav text-center center-block">
          <%= render partial: "experiment/category", collection: @experiment_settings.categories %>
        </ul>
      </div>
    </div>
  </nav>
</div>


<div id="page">

</div>



<div id="slogan-row" class="row">
  <div class="col-md-12">
    <div class="well text-center">
      <strong><%= @experiment_settings.slogan %></strong>
    </div>
  </div>
</div>

<!-- Bootstrapping Procedures -->
<script>
  var experiment_group_bootstrap = <%= @experiment_settings.to_json.html_safe %>;
  var experiment_bootstrap = <%= @experiment.to_json.html_safe %>
</script>


<!-- Home Page Template -->
<script id="home-template" type="x-tmpl-mustache">
  <div class="col-sm-3" id="side-menu">
    <div class="list-group">
      {{#attributes.categories}}
        <a href="#/category/{{id}}" class="list-group-item side-menu-category">{{name}}</a>
      {{/attributes.categories}}
    </div>
  </div>

  <div class="col-sm-9 text-center">
    <div id="front-page-image-slider" class="carousel slide center-block" data-ride="carousel">
      <!-- Indicators-->
      <ol class="carousel-indicators">
        <li data-target="#front-page-image-slider" data-slide-to="0" class="active"></li>
        <li data-target="#front-page-image-slider" data-slide-to="1"></li>
        <li data-target="#front-page-image-slider" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for Slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img src="{{attributes.front_image_1.url}}"/>
        </div>
        <div class="item">
          <img src="{{attributes.front_image_2.url}}"/>
        </div>
        <div class="item">
          <img src="{{attributes.front_image_3.url}}"/>
        </div>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#front-page-image-slider" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#front-page-image-slider" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>

</script>

<script id="product-template" type="x-tmpl-mustache">
        <div class="thumbnail">
          <div class="caption top">
            <h4 class="pull-left price">${{attributes.price}}</h4>
            <h4 class="pull-right price">${{attributes.price}}</h4>
            <button class="btn btn-primary btn-large pull-left add-to-cart">Add to Cart</button>
            <button class="btn btn-primary btn-large pull-right add-to-cart">Add to Cart</button>
            <div class="clearfix"></div>
          </div>
          <img src="{{attributes.main_image_url}}" alt=""/>
          <div class="caption bottom">
            <h4><a href="#/product/{{attributes.id}}" class="product-title">{{attributes.title}}</a></h4>
            <p class="description">{{attributes.description}}</p>
            <h4 class="pull-left price">${{attributes.price}}</h4>
            <h4 class="pull-right price">${{attributes.price}}</h4>
            <button class="btn btn-primary btn-large pull-left add-to-cart">Add to Cart</button>
            <button class="btn btn-primary btn-large pull-right add-to-cart">Add to Cart</button>
            <div class="clearfix"></div>
          </div>
        </div>
</script>

<script id="product-without-link-template" type="x-tmpl-mustache">
        <div class="thumbnail">
          <div class="caption top">
            <h4 class="pull-left price">${{attributes.price}}</h4>
            <h4 class="pull-right price">${{attributes.price}}</h4>
            <button class="btn btn-primary btn-large pull-left add-to-cart">Add to Cart</button>
            <button class="btn btn-primary btn-large pull-right add-to-cart">Add to Cart</button>
            <div class="clearfix"></div>
          </div>
          <img src="{{attributes.main_image_url}}" alt=""/>
          <div class="caption bottom">
            <h4>{{attributes.title}}</h4>
            <p class="description">{{attributes.description}}</p>
            <h4 class="pull-left price">${{attributes.price}}</h4>
            <h4 class="pull-right price">${{attributes.price}}</h4>
            <button class="btn btn-primary btn-large pull-left add-to-cart">Add to Cart</button>
            <button class="btn btn-primary btn-large pull-right add-to-cart">Add to Cart</button>
            <div class="clearfix"></div>
          </div>
        </div>
</script>

<script id="product-detail-template" type="x-tmpl-mustache">
  <div class="col-sm-3" id="return-menu">
    <div class="list-group">
      <a href="#/category/{{attributes.category_id}}" class="list-group-item" id="back-to-category" data-category="{{attributes.category_id}}">Back to Product List</a>
      <a href="#/home" class="list-group-item" id="back-to-home">Back to Home Page</a>
    </div>
  </div>
  <div class="col-sm-9" id="product-detail">
    <div class="thumbnail center-block">
      <div class="caption-full top">
        <h4 class="pull-left price">{{attributes.price}}</h4>
        <h4 class="pull-right price">{{attributes.price}}</h4>
        <button class="btn btn-primary btn-large pull-left add-to-cart">Add to Cart</button>
        <button class="btn btn-primary btn-large pull-right add-to-cart">Add to Cart</button>
        <div class="clearfix"></div>
      </div>
      <img class="img-responsive" src="{{attributes.main_image_url}}" alt=""/>
      <div class="caption-full bottom">
        <h4>{{attributes.name}}</h4>
        <p>{{attributes.description}}</p>
        <h4 class="pull-left price">{{attributes.price}}</h4>
        <h4 class="pull-right price">{{attributes.price}}</h4>
        <button class="btn btn-primary btn-large pull-left add-to-cart">Add to Cart</button>
        <button class="btn btn-primary btn-large pull-right add-to-cart">Add to Cart</button>
        <div class="clearfix"></div>
      </div>
    </div>
    <br/>
    <div class="row center-block" id="product-images">
    {{#attributes.product_images}}
      <div class="col-sm-6">
        <div class="thumbnail">
          <img src="{{filename.url}}" alt="" />
        </div>
      </div>
    {{/attributes.product_images}}
    </div>
  </div>
  <div class="clearfix"></div>
</script>

<script id="shopping-cart-template" type="x-tmpl-mustache">
  <div id="shopping-cart-page" class="center-block">
    <div class="page-title">
      <h1 class="text-center">Shopping Cart</h1>
    </div>
    <section id="cart" class="col-md-12">
      <table class="table table-striped">
        <thead>
            <tr>
              <th>Title</th>
              <th>Price</th>
              <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
      </table>
      <div class="center-block text-center">
        <a href="#/checkout" class="btn btn-danger btn-large checkout" id="checkout-button">Proceed to Checkout</a>
      </div>
    </section>
  </div>
</script>

<script id="shopping-cart-item-template" type="x-tmpl-mustache">
      <td>{{attributes.title}}</td>
      <td>{{attributes.price}}</td>
      <td><button class="btn btn-danger remove-item-from-cart">Remove From Cart</button></td>
</script>

<script id="checkout-with-survey-link-template" type="x-tmpl-mustache">
       <h3 class="text-center">The experiment has ended. Please proceed to the survey, by clicking the link below</h3>
       <a target="_blank" href="{{attributes.survey_link}}" class="center-block btn btn-large btn-primary">Go To Survey</a>
</script>

<script id="checkout-without-survey-link-template" type="x-tmpl-mustache">
       <h3 class="text-center">The experiment has ended. Please click below to exit the system.</h3>
       <%= link_to "Close", end_participation_path, class: "center-block btn btn-large btn-primary" %>
</script>