config/routes.rb
Rails.application.routes.draw do

  get 'experiment_result_package/edit'

  root 'experiment#home2'

  get 'select-experiment' => 'experiment#home2'

  get 'home' => 'experiment#home2'

  get 'experiment_results/create'

  get 'purchases/create'

  get 'product_categories/index'

  resources :experiment_groups
  resources :experiment_clicks
  resources :experiment_product_selects
  resources :experiment_product_views
  resources :experiment_category_views
  resources :experiment_product_detail_views
  resources :purchases
  resources :experiment_results
  resources :experiment, only: [:index]
  resources :participants, only: [:create]
  resources :experiment_result_package, only: [:update]

  post 'participants/:access_token/select-experiment' => 'participants#select_experiment'
  get 'product_categories/:id/:access_token' => 'product_categories#show'

  get 'experiment/home'

  post   'new_participant'   => 'sessions#create'
  delete 'end_participation'  => 'sessions#destroy'

  get 'select_experiment'     => 'sessions#select_experiment'
  post 'assign_experiment_group' =>  'sessions#assign_experiment_group'
  get 'assign_experiment_group/:experiment_id' => 'sessions#assign_experiment_group', as: 'assign_to_group'

  devise_for :admins,
             controllers: {
                 sessions: 'admins/sessions',
                 registrations: 'admins/registrations'
             },
             path: '/admin',
             path_names: {
                 sign_in: 'login'
             }

  namespace :admin do
    root :to => "static_pages#index"
    get 'experiment_results/home'
    get 'experiment_results/index/experiment/:id'   => 'experiment_results#index', as: :experiment_results_home_index
    delete 'experiment_results/index/experiment/:id' => 'experiment_results#destroy', as: :experiment_results_home_destroy 
    get 'experiment_results/purchases/participant/:id' => 'experiment_results#purchases', as: :experiment_results_purchases
    resources :experiments do
      resources :experiment_groups
    end
    put 'experiments/:id/make_available/' => 'experiments#make_available', as: :make_experiment_available
    put 'experiments/:id/make_unavailable' => 'experiments#make_unavailable', as: :make_experiment_unavailable
    resources :experiment_groups
    get 'experiment_groups/:experiment_id/add_to_experiment' => 'experiment_groups#add_to_experiment', as: :add_to_experiment
    get 'experiment_groups/:experiment_id/show_groups' => 'experiment_groups#index', as: :show_experiment_groups
    get 'experiment_groups/:id/add_all_categories' => 'experiment_groups#add_all_categories', as: :add_all_categories
    get 'experiment_groups/:id/delete_all_categories' => 'experiment_groups#delete_all_categories', as: :delete_all_categories
    get 'experiment_groups/group/:group_id/category/:category_id/remove_category' => 'experiment_groups#destroy_category', as: :destroy_category
    get 'experiment_groups/group/:group_id/category/:category_id/add_category' => 'experiment_groups#add_category', as: :add_category
    resources :categories do
      get 'products_by_category' => 'products#index_by_category'
      resources :products
    end
    resources :products do
      resources :product_images
    end
    get 'product-categories/' => 'products#product_categories_home', as: :home_products
    resources :product_images
    get 'product_images/:product_id/new' => 'product_images#new', as: :new_product_image
    get 'product_images/make_main_image/product/:product_id/image/:product_image_id' => 'product_images#make_main_image', as: :make_main_image
    post 'save-group-category-order' => 'experiment_group_categories#save_group_category_order'
  end

end

app/models/experiment.rb
# == Schema Information
#
# Table name: experiments
#
#  id                       :integer          not null, primary key
#  name                     :string
#  available                :boolean
#  survey_link              :string
#  experiment_group_counter :integer          default(0)
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  completion_message       :string
#  show_survey_link         :boolean
#

class Experiment < ActiveRecord::Base
  # Scopes
  scope :available, -> { where(available: true)}

  has_many :experiment_groups, autosave: true, dependent: :delete_all

  # Has Many Experiment Results
  has_many :experiment_results, -> { order('created_at ASC') }, inverse_of: :experiment

  # Has Many Clicks
  has_many :experiment_clicks,  -> { order('created_at ASC') },inverse_of: :experiment

  # Has Many Product Placements
  has_many :experiment_product_placements, -> { order('created_at ASC') }, inverse_of: :experiment

  # Has Many Product Selects
  has_many :experiment_product_selects, -> { order('created_at ASC') }, inverse_of: :experiment

  # Has Many Product Views
  has_many :experiment_product_views, -> { order('created_at ASC') }, inverse_of: :experiment

  # Has Many Experiment Category Views
  has_many :experiment_category_views, -> { order('created_at ASC') }, inverse_of: :experiment 

  # Has Many Experiment Product Detail Views
  has_many :experiment_product_detail_views, -> { order('created_at ASC') }, inverse_of: :experiment

  # Has Many Purchases
  has_many :experiment_purchases, -> { order('created_at ASC') }, inverse_of: :experiment

  # Has Many Participants
  has_many :participants, -> { order('created_at ASC') }, inverse_of: :experiment

  validates :name, presence: true
end

app/controllers/admin/experiments_controller.rb
class Admin::ExperimentsController < ApplicationController
  layout "admin"
  before_action :authenticate_admin!

  def index
    @experiments = Experiment.all
  end

  def show
    @experiment = Experiment.includes(:experiment_groups).find(params[:id])
  end

  def new
    @experiment = Experiment.new
  end

  def create
    experiment = Experiment.new(experiment_params)
    if experiment.save
      flash[:success] = "Experiment, #{experiment.name}, was successfully created"
      redirect_to admin_experiment_path(experiment)
    else
      flash[:error] = "An error occurred. Please try again"
      redirect_to new_admin_experiment_path
    end
  end

  def edit
    @experiment = Experiment.find(params[:id])
  end

  def update
    experiment = Experiment.find_by({id: params[:id]})
    if experiment.update_attributes(experiment_params)
      redirect_to admin_experiment_path experiment
    end
  end

  def destroy
    @experiment = Experiment.find(params[:id])
    if @experiment.destroy
      flash[:success] = 'The experiment has been successfully deleted'
      redirect_to admin_experiments_path
    else
      flash[:error] = 'There was a problem in attempting to delete the experiment. Please try again. If the problem persists, contact your administrator'
      redirect_to admin_experiment_path @experiment
    end
  end

  def make_available
    experiment = Experiment.find(params[:id])
    experiment.available = true
    if experiment.save
      redirect_to admin_experiment_path experiment
    end
  end

  def make_unavailable
    experiment = Experiment.find(params[:id])
    experiment.available = false
    if experiment.save
      redirect_to admin_experiment_path experiment
    end
  end

  private
    def experiment_params
      params.require(:experiment).permit(:name, :available, :survey_link, :show_survey_link, :completion_message)
    end
end

app/controllers/experiment_controller.rb
class ExperimentController < ApplicationController
  layout 'application'


  def home
    @experiment_settings = ExperimentGroup.includes(:categories).find_by_id(current_participant.experiment_group)
    @experiment = Experiment.find(@experiment_settings.experiment_id)
  end

  def home2

  end

  def index
    @experiments = Experiment.includes(experiment_groups: [experiment_group_categories: [:category]]).available
    respond_to do |format|
      format.json {
          render :json => @experiments.to_json(:include => {
              :experiment_groups => {
                  :include => {
                      :experiment_group_categories => {
                          :include => :category
                      }
                  }
              }
          })
      }
    end
  end

end

app/helpers/admin/experiments_helper.rb
module Admin::ExperimentsHelper
end

app/helpers/experiment_helper.rb
module ExperimentHelper
end

app/views/admin/experiments/_experiment.html.erb
<% if experiment.available
     available = 'Yes'
   else
     available = 'No'
   end
%>

<tr>
  <td><%= experiment.name %></td>
  <td><%= experiment.experiment_groups.size %></td>
  <td><%= available %></td>
  <td><%= link_to "View", admin_experiment_path(experiment), class: "btn btn-primary" %></td>
</tr>

app/views/admin/experiments/edit.html.erb
<%
   @pagetitle = 'Edit Experiment'
   @page_class = 'experiments new'
%>

<h1 class="text-center">Edit Experiment - #{@experiment.name}</h1>

<%= render partial: 'layouts/messages' %>

<div class="well well-lg">
    <%= form_for [:admin, @experiment] do |f| %>
        <div class="form-group">
          <%= f.label :name, "Experiment Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.check_box :available %>
          <%= f.label :available, "Available" %>
        </div>

        <div class="form-group">
            <%= f.label :completion_message, "Completion Message" %>
            <%= f.text_field :completion_message, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.check_box :show_survey_link %>
          <%= f.label :show_survey_link, "Show Survey Link" %>
        </div>

        <div class="form-group">
          <%= f.label :survey_link, "Survey Link" %>
          <%= f.text_field :survey_link, class: "form-control" %>
        </div>

        <%= f.submit "Save", class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/admin/experiments/index.html.erb
<h1 class="text-center">List of Experiments</h1>
<table class="table">
  <thead>
    <tr>
      <th>Experiment Name</th>
      <th>Experimental Groups</th>
      <th>Available?</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render @experiments %>
  </tbody>
</table>

app/views/admin/experiments/new.html.erb
<%
   @pagetitle = 'Create New Experiment'
   @page_class = 'experiments new'
%>

<h1 class="text-center">Create New Experiment</h1>

<%= render partial: 'layouts/messages' %>

<div class="well well-lg">
    <%= form_for [:admin, @experiment] do |f| %>
        <div class="form-group">
          <%= f.label :name, "Experiment Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.check_box :available %>
          <%= f.label :available, "Available" %>
        </div>

        <div class="form-group">
            <%= f.label :completion_message, "Completion Message" %>
            <%= f.text_field :completion_message, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.check_box :show_survey_link %>
          <%= f.label :show_survey_link, "Show Survey Link" %>
        </div>

        <div class="form-group">
          <%= f.label :survey_link, "Survey Link" %>
          <%= f.text_field :survey_link, class: "form-control" %>
        </div>

        <%= f.submit "Add Experiment", class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/admin/experiments/show.html.erb
<%
   @pagetitle = "Experiment: #{@experiment.name}"
   @page_class = 'experiments show'
%>

<h1 class="text-center">Experiment: <%= @experiment.name %></h1>

<%= render partial: 'layouts/messages' %>

<%= link_to "Edit Experiment", edit_admin_experiment_path(@experiment), class: "btn btn-primary" %>
<%= link_to "Delete Experiment", admin_experiment_path(@experiment), method: :delete, class: "btn btn-danger" %>
<!-- Availability Buttons -->
<% if @experiment.available %>
    <%= link_to "Make Experiment Unavailable", admin_make_experiment_unavailable_path(@experiment), method: :put, class: "btn btn-warning" %>
<% else %>
    <%= link_to "Make Experiment Available", admin_make_experiment_available_path(@experiment), method: :put, class: "btn btn-warning" %>
<% end %>
<div class="well well-lg">
  <h4><u>Available to Subjects:</u></h4>
  <p><%= @experiment.available ? 'Yes' : 'No' %></p>
  <h4><u>Completion Message:</u></h4>
  <p><%= @experiment.completion_message %></p>
  <h4><u>Show Survey Link:</u></h4>
  <p><%= @experiment.show_survey_link ? 'Yes' : 'No' %></p>
  <h4><u>Survey Link</u></h4>
  <p><%= link_to @experiment.survey_link, @experiment.survey_link %></p>
  <% if @experiment.experiment_groups.count > 0 %>
    <h4><u>Experimental Groups</u></h4>
      <table class="table table-striped">
        <thead>
            <th>Group No</th>
            <th></th>
        </thead>
        <tbody>
            <% @experiment.experiment_groups.each do |group| %>
                <tr>
                  <td><%= group.group_no %></td>
                  <td>
                    <div class='btn-group'>
                      <button type='button' class='btn btn-primary dropdown-toggle' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
                        Options <span class='caret'></span>
                      </button>
                      <ul class='dropdown-menu'>
                        <li><%= link_to "View", admin_experiment_experiment_group_path(@experiment, group) %></li>
                        <li role='separator' class='divider'></li>
                        <li><%= link_to "Edit", edit_admin_experiment_experiment_group_path(@experiment, group) %></li>
                        <li><%= link_to "Delete", admin_experiment_experiment_group_path(@experiment, group), method: :delete, data: {confirm: 'Are you sure you want to delete this experiment group?'} %></li>
                      </ul>
                    </div>
                  </td>
                </tr>
            <% end %>
        </tbody>
      </table>
  <% end %>
</div>
<!-- Add Experimental Group -->
<%= link_to "Add Experimental Group", new_admin_experiment_experiment_group_path(@experiment), class: "btn btn-primary" %>