config/routes.rb
Rails.application.routes.draw do

  get 'experiment_result_package/edit'

  root 'experiment#home2'

  get 'select-experiment' => 'experiment#home2'

  get 'home' => 'experiment#home2'

  get 'experiment_results/create'

  get 'purchases/create'

  get 'product_categories/index'

  resources :experiment_groups
  resources :experiment_clicks
  resources :experiment_product_selects
  resources :experiment_product_views
  resources :experiment_category_views
  resources :experiment_product_detail_views
  resources :purchases
  resources :experiment_results
  resources :experiment, only: [:index]
  resources :participants, only: [:create]
  resources :experiment_result_package, only: [:update]

  post 'participants/:access_token/select-experiment' => 'participants#select_experiment'
  get 'product_categories/:id/:access_token' => 'product_categories#show'

  get 'experiment/home'

  post   'new_participant'   => 'sessions#create'
  delete 'end_participation'  => 'sessions#destroy'

  get 'select_experiment'     => 'sessions#select_experiment'
  post 'assign_experiment_group' =>  'sessions#assign_experiment_group'
  get 'assign_experiment_group/:experiment_id' => 'sessions#assign_experiment_group', as: 'assign_to_group'

  devise_for :admins,
             controllers: {
                 sessions: 'admins/sessions',
                 registrations: 'admins/registrations'
             },
             path: '/admin',
             path_names: {
                 sign_in: 'login'
             }

  namespace :admin do
    root :to => "static_pages#index"
    get 'experiment_results/home'
    get 'experiment_results/index/experiment/:id'   => 'experiment_results#index', as: :experiment_results_home_index
    delete 'experiment_results/index/experiment/:id' => 'experiment_results#destroy', as: :experiment_results_home_destroy 
    get 'experiment_results/purchases/participant/:id' => 'experiment_results#purchases', as: :experiment_results_purchases
    resources :experiments do
      resources :experiment_groups
    end
    put 'experiments/:id/make_available/' => 'experiments#make_available', as: :make_experiment_available
    put 'experiments/:id/make_unavailable' => 'experiments#make_unavailable', as: :make_experiment_unavailable
    resources :experiment_groups
    get 'experiment_groups/:experiment_id/add_to_experiment' => 'experiment_groups#add_to_experiment', as: :add_to_experiment
    get 'experiment_groups/:experiment_id/show_groups' => 'experiment_groups#index', as: :show_experiment_groups
    get 'experiment_groups/:id/add_all_categories' => 'experiment_groups#add_all_categories', as: :add_all_categories
    get 'experiment_groups/:id/delete_all_categories' => 'experiment_groups#delete_all_categories', as: :delete_all_categories
    get 'experiment_groups/group/:group_id/category/:category_id/remove_category' => 'experiment_groups#destroy_category', as: :destroy_category
    get 'experiment_groups/group/:group_id/category/:category_id/add_category' => 'experiment_groups#add_category', as: :add_category
    resources :categories do
      get 'products_by_category' => 'products#index_by_category'
      resources :products
    end
    resources :products do
      resources :product_images
    end
    get 'product-categories/' => 'products#product_categories_home', as: :home_products
    resources :product_images
    get 'product_images/:product_id/new' => 'product_images#new', as: :new_product_image
    get 'product_images/make_main_image/product/:product_id/image/:product_image_id' => 'product_images#make_main_image', as: :make_main_image
    post 'save-group-category-order' => 'experiment_group_categories#save_group_category_order'
  end

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  has_many :products, inverse_of: :category, dependent: :destroy 
  has_many :experiment_group_categories
  has_many :experiment_groups, through: :experiment_group_categories
  has_many :experiment_category_views, inverse_of: :category
  has_many :experiment_product_detail_views, inverse_of: :category
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  layout "admin"
  before_action :authenticate_admin!

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "The category, #{@category.name}, was successfully created"
      redirect_to admin_categories_path
    else
      flash[:error] = 'There was an error in attempting to add a new category. Please try again. If the problem persists, please contact your administrator.'
      redirect_to new_admin_category_path
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to admin_categories_path
    else
      flash[:error] = 'There was an error in attempting to add a new category. Please try again. If the problem persists, please contact your administrator.'
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      redirect_to admin_categories_path
    else
      flash[:error] = 'There was an error in attempting to delete the category. Please try again. If the problem persists, please contact your administrator.'
      redirect_to admin_categories_path
    end
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_category.html.erb
<tr>
  <td><%= category.name %></td>
  <td>
    <div class='btn-group'>
      <button type='button' class='btn btn-primary dropdown-toggle' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
        Options <span class='caret'></span>
      </button>
      <ul class='dropdown-menu'>
        <li><%= link_to "Edit Category Name", edit_admin_category_url(category) %></li>
        <li><%= link_to "Delete Category", admin_category_path(category), method: :delete, data: {confirm: "Are you sure you want to delete this category?"} %></li>
        <li role='separator' class='divider'></li>
        <!-- TODO Add View Category Products -->
        <!-- TODO Add Product to Category -->
      </ul>
    </div>
  </td>
</tr>

app/views/admin/categories/edit.html.erb
<h1>Edit Product Category</h1>
<%= form_for [:admin, @category] do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, class: "form-control" %>

    <br/>

    <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/admin/categories/index.html.erb
<%
   @pagetitle = 'Product Categories'
   @page_class = 'categories index'
%>

<%= link_to "Add Category", new_admin_category_path, class: "btn btn-primary center-block text-center" %>


<h1 class="text-center">Product Categories</h1>

<%= render partial: 'layouts/messages' %>

<table class="table table-striped">
  <thead>
    <th>Category</th>
    <th></th>
  </thead>
  <tbody>
    <%= render @categories %>
  </tbody>
</table>

app/views/admin/categories/new.html.erb
<%
   @pagetitle = 'Create New Product Category'
   @page_class = 'categories new'
%>

<%= render partial: 'layouts/messages' %>


<div class="well well-lg">
    <h1 class="text-center">Add New Product Category</h1>
    <%= form_for [:admin, @category] do |f| %>
      <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <%= f.submit "Add", class: "btn btn-primary" %>
    <% end %>
</div>