config/routes.rb
Rails.application.routes.draw do

  get 'experiment_result_package/edit'

  root 'experiment#home2'

  get 'select-experiment' => 'experiment#home2'

  get 'home' => 'experiment#home2'

  get 'experiment_results/create'

  get 'purchases/create'

  get 'product_categories/index'

  resources :experiment_groups
  resources :experiment_clicks
  resources :experiment_product_selects
  resources :experiment_product_views
  resources :experiment_category_views
  resources :experiment_product_detail_views
  resources :purchases
  resources :experiment_results
  resources :experiment, only: [:index]
  resources :participants, only: [:create]
  resources :experiment_result_package, only: [:update]

  post 'participants/:access_token/select-experiment' => 'participants#select_experiment'
  get 'product_categories/:id/:access_token' => 'product_categories#show'

  get 'experiment/home'

  post   'new_participant'   => 'sessions#create'
  delete 'end_participation'  => 'sessions#destroy'

  get 'select_experiment'     => 'sessions#select_experiment'
  post 'assign_experiment_group' =>  'sessions#assign_experiment_group'
  get 'assign_experiment_group/:experiment_id' => 'sessions#assign_experiment_group', as: 'assign_to_group'

  devise_for :admins,
             controllers: {
                 sessions: 'admins/sessions',
                 registrations: 'admins/registrations'
             },
             path: '/admin',
             path_names: {
                 sign_in: 'login'
             }

  namespace :admin do
    root :to => "static_pages#index"
    get 'experiment_results/home'
    get 'experiment_results/index/experiment/:id'   => 'experiment_results#index', as: :experiment_results_home_index
    delete 'experiment_results/index/experiment/:id' => 'experiment_results#destroy', as: :experiment_results_home_destroy 
    get 'experiment_results/purchases/participant/:id' => 'experiment_results#purchases', as: :experiment_results_purchases
    resources :experiments do
      resources :experiment_groups
    end
    put 'experiments/:id/make_available/' => 'experiments#make_available', as: :make_experiment_available
    put 'experiments/:id/make_unavailable' => 'experiments#make_unavailable', as: :make_experiment_unavailable
    resources :experiment_groups
    get 'experiment_groups/:experiment_id/add_to_experiment' => 'experiment_groups#add_to_experiment', as: :add_to_experiment
    get 'experiment_groups/:experiment_id/show_groups' => 'experiment_groups#index', as: :show_experiment_groups
    get 'experiment_groups/:id/add_all_categories' => 'experiment_groups#add_all_categories', as: :add_all_categories
    get 'experiment_groups/:id/delete_all_categories' => 'experiment_groups#delete_all_categories', as: :delete_all_categories
    get 'experiment_groups/group/:group_id/category/:category_id/remove_category' => 'experiment_groups#destroy_category', as: :destroy_category
    get 'experiment_groups/group/:group_id/category/:category_id/add_category' => 'experiment_groups#add_category', as: :add_category
    resources :categories do
      get 'products_by_category' => 'products#index_by_category'
      resources :products
    end
    resources :products do
      resources :product_images
    end
    get 'product-categories/' => 'products#product_categories_home', as: :home_products
    resources :product_images
    get 'product_images/:product_id/new' => 'product_images#new', as: :new_product_image
    get 'product_images/make_main_image/product/:product_id/image/:product_image_id' => 'product_images#make_main_image', as: :make_main_image
    post 'save-group-category-order' => 'experiment_group_categories#save_group_category_order'
  end

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                    :integer          not null, primary key
#  title                 :string
#  price_cents           :integer
#  description           :text
#  category_id           :integer
#  main_product_image_id :integer
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#

class Product < ActiveRecord::Base
  # Product has many images
  has_many :product_images, inverse_of: :product,  autosave: true, dependent: :delete_all

  # Product belongs to a product category
  belongs_to :category, inverse_of: :products

  # Product has been placed in many experiments
  has_many :experiment_product_placements, inverse_of: :product

  # Product has been selected in many experiments
  has_many :experiment_product_selects, inverse_of: :product

  # Product has been viewed in many experiments
  has_many :experiment_product_views, inverse_of: :product

  # Product has been purchased in many experiments
  has_many :experiment_purchases, inverse_of: :product

  # Apply Monetize gem to Price Column
  monetize :price_cents

  validates :title, presence: true

  def as_json(options={})
    super(include: [:product_images])
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin"
  before_action :authenticate_admin!

  def new
    @product = Product.new
  end

  def create
    product = Product.new(product_params)
    if product.save
      flash[:success] = "The product, #{product.title}, was successfully created"
      redirect_to admin_products_path
    else
      flash[:error] = 'There was an error in attempting to add a new product. Please try again. If the problem persists, please contact your administrator.'
      redirect_to new_admin_product_path
    end
  end

  def show
    @product = Product.includes(:category).find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    product = Product.find(params[:id])
    if product.update(product_params)
      flash[:success] = 'The product was successfully updated'
      redirect_to admin_product_path(product)
    else
      flash[:error] = 'There was an error in attempting to update the product. Please try again. If the problem persists, please contact your administrator.'
      redirect_to edit_admin_product_path(params[:id])
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to admin_category_products_path @product.category_id
    else
      flash[:error] = 'There was an error in attempting to delete the product. Please try again. If the problem persists, please contact your administrator.'
      redirect_to admin_product_path @product
    end
  end

  def index
    @products = Product.includes(:category).all
  end

  def index_by_category
    @products = Product.where(category_id: params[:category_id])
    @category = Category.find(params[:category_id])
  end

  def product_categories_home
    @categories = Category.all
  end

  private
    def product_params
      params.require(:product).permit(:title, :description, :price, :category_id)
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_category_product.html.erb
<tr>
  <td><%= category_product.title %></td>
  <td><%= humanized_money_with_symbol category_product.price %></td>
  <td>
    <div class='btn-group'>
      <button type='button' class='btn btn-primary dropdown-toggle' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
        Options <span class='caret'></span>
      </button>
      <ul class='dropdown-menu'>
        <li><%= link_to "View", admin_product_path(category_product) %></li>
        <li role='separator' class='divider'></li>
        <li><%= link_to "Edit", edit_admin_product_path(category_product) %></li>
        <li><%= link_to "Delete", admin_product_path(category_product), method: :delete, data: {confirm: 'Are you sure you want to delete this product?'} %></li>
      </ul>
    </div>
  </td>
</tr>

app/views/admin/products/_product.html.erb
<tr>
  <td><%= product.title %></td>
  <td><%= humanized_money_with_symbol product.price %></td>
  <td><%= product.category.name %></td>
  <td>
    <div class='btn-group'>
      <button type='button' class='btn btn-primary dropdown-toggle' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
        Options <span class='caret'></span>
      </button>
      <ul class='dropdown-menu'>
        <li><%= link_to "View", admin_product_path(product) %></li>
        <li role='separator' class='divider'></li>
        <li><%= link_to "Edit", edit_admin_product_path(product) %></li>
        <li><%= link_to "Delete", admin_product_path(product), method: :delete, data: {confirm: 'Are you sure you want to delete this product?'} %></li>
      </ul>
    </div>
  </td>
</tr>

app/views/admin/products/edit.html.erb
<%
   @pagetitle = 'Product Categories'
   @page_class = 'categories edit'
%>

<h1 class="text-center">Edit Product: <%= @product.title %></h1>

<%= render partial: 'layouts/messages' %>

<div class="well well-lg">
  <%= form_for [:admin, @product] do |f| %>
      <div class="form-group">
        <%= f.label :title, "Display Title" %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description, "Product Description" %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :price, "Price" %>
        <%= f.text_field :price, class: "form-control", data: { role: 'money', aSign: '$', wEmpty: 'sign' } %>
      </div>

      <div class="form-group">
        <%= f.label :category_id, "Category" %>
        <%= f.collection_select :category_id, Category.all, :id, :name, {}, { class: "form-control" } %>
      </div>

      <%= f.submit "Save Changes", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/admin/products/index.html.erb
<%
   @pagetitle = 'All Products'
   @page_class = 'products index'
%>

<%= link_to "Add New Product", new_admin_product_path, class: "btn btn-primary text-center center-block" %>

<h1 class="text-center">All Products</h1>

<%= render partial: 'layouts/messages' %>

<table class="table table-striped">
  <thead>
    <th>Title</th>
    <th>Price</th>
    <th>Category</th>
    <th></th>
  </thead>
  <tbody>
    <%= render @products %>
</table>

app/views/admin/products/index_by_category.html.erb
<%
   @pagetitle = "Products for #{@category.name}"
   @page_class = 'products index'
%>

<h1 class="text-center">Products for <%= @category.name %></h1>

<%= render partial: 'layouts/messages' %>

<table class="table table-striped">
  <thead>
  <th>Title</th>
  <th>Price</th>
  <th></th>
  </thead>
  <tbody>
  <%= render partial: 'admin/products/category_product', collection: @products %>
</table>

app/views/admin/products/new.html.erb
<%
   @pagetitle = 'Product Categories'
   @page_class = 'categories index'
%>

<h1 class="text-center">Add New Product</h1>

<%= render partial: 'layouts/messages' %>

<div class="well well-lg">
    <%= form_for [:admin, @product] do |f| %>
      <div class="form-group">
        <%= f.label :title, "Display Title" %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description, "Product Description" %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :price, "Price" %>
        <%= f.text_field :price, class: "form-control", data: { role: 'money', aSign: '$', wEmpty: 'sign' } %>
      </div>

      <div class="form-group">
        <%= f.label :category_id, "Category" %>
        <%= f.collection_select :category_id, Category.all, :id, :name, {}, { class: "form-control" } %>
      </div>

      <%= f.submit "Add", class: "btn btn-primary" %>
    <% end %>
</div>

app/views/admin/products/product_categories_home.html.erb
<h2 class="text-center">Please select a product category</h2>
<div class="center-block text-center">
  <% @categories.each do |category| %>
      <% if category.products.size > 0 %>
        <%= link_to "#{category.name}", admin_category_products_by_category_path(category), class: "btn btn-default btn-large" %>
      <% else %>
        <%= link_to "#{category.name}", "#", class: "btn btn-default btn-large" %>
      <% end %>
  <% end %>
</div>

app/views/admin/products/show.html.erb
<%
   @pagetitle = 'All Products'
   @page_class = 'products show'
%>

<%= link_to "Back to Product List", admin_products_path, class: "btn btn-default text-center center-block" %>

<h1 class="text-center"><%= @product.title %></h1>

<%= render partial: 'layouts/messages' %>

<%= link_to "Edit", edit_admin_product_path(@product), class: "btn btn-warning" %>
<%= link_to "Delete", admin_product_path(@product), method: :delete, class: "btn btn-danger", data: {confirm: 'Are you sure you want to delete this product?'} %>
<%= link_to "Add New Image", new_admin_product_product_image_path(@product), class: "btn btn-primary" %>

<div class="well well-lg">
  <h4><u>Category</u></h4>
  <p><%= @product.category.name %></p>
  <h4><u>Price</u></h4>
  <p><%= humanized_money_with_symbol @product.price %></p>
  <h4><u>Description</u></h4>
  <p><%= @product.description %></p>
  <h4><u>Images</u></h4>
  <div class="row">
    <%= render partial: 'admin/product_images/product_image', collection: @product.product_images, locals: {main_image: @product.main_product_image_id.nil? ? 0: @product.main_product_image_id} %>
    <div class="clearfix"></div>
  </div>
</div>